language: node_js
git:
  depth: 3
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run cov

deploy:
  - provider: script
    script: npm run cov:send
    skip_cleanup: true
  - provider: script
    script: 
      npm run all &&
      git config --local user.name "travis@travis-ci.org" &&
      git config --local user.email "Travis CI" &&
      gh-pages -m \"[ci skip] Updates\" -r https://$GH_TOKEN@github.com/anasceym/prom2json-stream.git -d build/docs &&
      npm publish
    skip_cleanup: true
    on:
      tags: true
