language: node_js
git:
  depth: 3
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run cov

before_deploy:
  if ! [[ $DEPLOYMENT_SETUP ]]; then
    export DEPLOYMENT_SETUP="true" &&
    npm run ci:prepare-release &&
    git config --local user.name "travis@travis-ci.org" &&
    git config --local user.email "Travis CI" &&
    git remote add origin-ci https://${GH_TOKEN}@github.com/anasceym/prom2json-stream.git;
  fi

deploy:
  - provider: script
    script: npm run cov:send
    skip_cleanup: true
  - provider: script
    script: 
      - npm run ci:doc:publish
      - git push --follow-tags origin-ci master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm publish
    skip_cleanup: true
    on:
      tags: true
