language: node_js
git:
  depth: 3
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run cov

deploy:
  - provider: script
    script: npm run cov:send
    skip_cleanup: true
  - provider: script
    script: npm publish
    skip_cleanup: true
    on:
      tags: true
