language: node_js
git:
  depth: 3
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run cov

before_deploy:
  if ! [[ $DEPLOYMENT_SETUP ]]; then
    export DEPLOYMENT_SETUP="true" &&
    git config --local user.name "$USER_NAME" &&
    git config --local user.email "$USER_EMAIL" &&
    npm run ci:prepare-release
  fi

deploy:
  - provider: script
    script: npm run cov:send
    skip_cleanup: true
  - provider: script
    script: npm run ci:doc:publish && git push --follow-tags origin master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm publish
    skip_cleanup: true
    on:
      tags: true
