language: node_js
git:
  depth: 3
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run cov

before_deploy:
  - git config --local user.name "travis@travis-ci.org"
  - git config --local user.email "Travis CI"
  - npm run ci:prepare-release

deploy:
  - provider: script
    script: npm run cov:send
    skip_cleanup: true
  - provider: script
    script: git push --follow-tags origin master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm publish
    skip_cleanup: true
    on:
      tags: true
